### ISSUE TITLE
水产采购单需要增加一列计量单位“重量”，现有的“数量”填写条数、个数

### ISSUE THREAD

**Issue by yzcyyun** [jonahfang/yzcycnproject#106]
1、水产采购情况较为特殊，餐厅订货按条数、个数较多，而核算金额以重量为准；
2、且水产的个体重量大小对单价的影响较大，个体越大越重、单价普遍越高；
3、在采购单中填写条数、个数，便于把控价格，应对餐厅询价等情况。

**Comment by jonahfang** [comment]
已修改。
