### ISSUE TITLE
录入订单时用鼠标操作，数据不能保存完整

### ISSUE THREAD

**Issue by yzcyyun** [jonahfang/yzcycnproject#63]
录入订单时用鼠标操作，再点击“保存并开新单”，会出现只能保存部分订单品种的情况。
如果用键盘操作则无问题。

**Comment by jonahfang4ty** [comment]
是否是最后一个商品没有保存？能再现吗（即每次都这样吗）？

**Comment by yzcyyun** [comment]
昨天试用中录了十几份订单，都出现这种情况，但如果点击“保存并关闭”便能正常保存。

**Comment by jonahfang4ty** [comment]
部分保存有什么规律吗？是否只是最后一个商品没有保存？

**Comment by jonahfang4ty** [comment]
我刚才操作了 一下是好的，看看有什么规律没有

**Comment by yzcyyun** [comment]
好的，我再试一下

**Comment by yzcyyun** [comment]
录入订单，完全用鼠标操作时，会有红色标注提示。
如果在最后一个录入的商品结尾用回车，红色标注便会全部消失。
此时点击“保存并新开单”或“保存并关闭”，然后查看刚才录入的订单，都只保存了最后一个商品，即末尾用回车操作的那个。

**Comment by jonahfang4ty** [comment]
这样操作不对

**Comment by jonahfang4ty** [comment]
每个商品都要最后在备注一栏按回车才是保存，只要有红色的都表示没有保存
